### ISSUE TITLE
Functions "Delete original file" and "Group by directories" do not work correctly

### ISSUE THREAD

**Issue by cmdrklepto** [NoFoolLikeOne/EDMC-Screenshot#11]
Hello! Sorry for my English.
The original file is deleted in any case. Regardless of the setting of the checkbox "Delete original file". That is always.
Correct numbering of screenshots occurs only when the function "Group by directories" is selected. If the function is disabled, the last file is always overwritten and it is impossible to make several consecutive screenshots.

**Comment by NoFoolLikeOne** [comment]
Looking into it

**Comment by cmdrklepto** [comment]
Thanks. And thanks for your plugin, I think it is the one of the best :) Simple, but very important)

**Comment by NoFoolLikeOne** [comment]
Release 3.3.0
