### ISSUE TITLE
Stuck processing screenshot

### ISSUE THREAD

**Issue by bambi72** [NoFoolLikeOne/EDMC-Screenshot#22]
I have just installed your plugin and it seems to get stuck converting the BMP to PNG.

I have the paths set for the screenshots
D:\Users\user name\Pictures\Frontier Developments\Elite Dangerous
and output
D:\Users\user name\Pictures\Frontier Developments\Elite Dangerous\EDMC

I have tried it with the group files by system directory on and off

**Comment by NoFoolLikeOne** [comment]
Can you look in the log file and let me know what errors you get.

%TMP%\EDMarketConnector.log

Also does your username have any special characters?

**Comment by bambi72** [comment]
I saw the closed issue and I have no special characters.
event: Screenshot

[Screenshot] display: 0
[Screenshot] C:\Users\Danny Cooper\Saved Games\Frontier Developments\Elite Dangerous\status.json
Traceback (most recent call last):
  File "plug.pyo", line 292, in notify_journal_entry
  File "C:\Users\my name\AppData\Local\EDMarketConnector\plugins\EDMC-Screenshot\load.py", line 373, in journal_entry
  File "C:\Users\my name\AppData\Local\EDMarketConnector\plugins\EDMC-Screenshot\load.py", line 344, in getGuiFocus
IOError: [Errno 2] No such file or directory: 'C:\\Users\\my name\\Saved Games\\Frontier Developments\\Elite Dangerous\\status.json'

I guess its the double \\  ?

**Comment by NoFoolLikeOne** [comment]
So its saying that status.json does not exist. If you stop and restart EDMC are you able to take a screenshot or does it have the same error every time you use it?

**Comment by bambi72** [comment]
Its the same error in the logs every time.
IOError: [Errno 2] No such file or directory: 'C:\\Users\\user name\\Saved Games\\Frontier Developments\\Elite Dangerous\\status.json'
with a double \ between each folder name.

**Comment by NoFoolLikeOne** [comment]
I don't think the double slash is an issue. 

Does that path actually exist? If you open file explorer and paste in the path name does it open the status.json file?

**Comment by bambi72** [comment]
I  have figured the problem, my user folders are on the D drive, it is set to D:\Users\user name\Saved Games\Frontier Developments\Elite Dangerous in EDMC but the plugin is looking on C:\
This doesn't seem to affect other plugins I have running that read the journal.

I just tried editing the load.py file to hardcode my path to the json file rather than using %userprofiles% and its worked.

**Comment by NoFoolLikeOne** [comment]
Thanks for the update. I'll have a look in the edmc config module and see if it gives me the proper location and I'll deliver a patch.

**Comment by NoFoolLikeOne** [comment]
Fixed in Release 3.0.2
