### ISSUE TITLE
doesn't seem to work... show me how dumb i can be

### ISSUE THREAD

**Issue by mrmauz** [NoFoolLikeOne/EDMC-Screenshot#23]
sorry to bother you but i can't figure how to make it work: when i tap f10 it changes its status to "processing screenshot" and stands there for some time doing nothing or, at worst crashing edmc... what am i doing wrong?

**Comment by NoFoolLikeOne** [comment]
You need to make sure you have configured the directories correctly

Screenshot Directory: C:\Users\YOURUSERNAME\Pictures\Frontier Developments\Elite Dangerous

The Conversion directory can be the same as the screenshot directory or you can gie a directory on a different drive. 

Make sure both directories exist and that Elite Dangerous is writing to the screenshot directory

**Comment by mrmauz** [comment]
that was the culprit, as stated before the n00biness is strong with me! i was trying to have the plugin referring to the windows games acquisition folder while obviously ED writes his screenshots to another folder. putting in the right address had the app working flawlessly (you don't say?) ;)

thanks again man, great and fast answer, will definitely support this
