### ISSUE TITLE
Converted screenshots are PNG format, but labelled JPG

### ISSUE THREAD

**Issue by hstracker90** [NoFoolLikeOne/EDMC-Screenshot#24]
Thank you for the plug-in, it works really great on my Win 8.1 machine.
I found a minor bug: the converted screenshot is labelled {systemname_number.jpg}, but it is in fact a PNG file. 
When I open it with IrfanView, it detects the discrepancy and renames the file, so it is a very minor inconvenience to click on "rename" once. But maybe you would like to correct it.

**Comment by NoFoolLikeOne** [comment]
Sorry I missed your issue. It is indeed a bug that appears in some circumstances.  Fixed in new release
