### ISSUE TITLE
Processing image hangs in Sagittarius A*

### ISSUE THREAD

**Issue by robertpateii** [NoFoolLikeOne/EDMC-Screenshot#39]
Hello,

I think the * in Sagittarius A* is causing this plugin to hang during processing because * isn't a valid character in a file name on Windows (and perhaps other systems too).

**Reproduction steps for error:**
Be running Windows 10
Have file mask set to include System
Fly to Sagittarius A* 😆 
Take a screenshot
Processing hang

**Reproduction steps for success:**
Still be in Sagittarius A*
Change the file mask to exclude system and just include body
Take a screenshot
No processing hang!

**Comment by NoFoolLikeOne** [comment]
I shall get this sorted in 5.0.1

**Comment by IvIePhisto** [comment]
I can report this is still an issue.
