### ISSUE TITLE
Plugin doesn't activate in EDMC

### ISSUE THREAD

**Issue by romesc** [NoFoolLikeOne/EDMC-Screenshot#4]
I installed some other plugins and this one. All other plugins have been enabled after restarting EDMC, except this one.
Can you help me with this?
Thks.

**Comment by NoFoolLikeOne** [comment]
Look in the log file in C:\Users\**<your username>**\AppData\Local\Temp\EDMarketConnector.log

Can you see any error messages?

**Comment by NoFoolLikeOne** [comment]
For some reason I can't quite understand, it was missing library files.

I have updated a new release 1.5 please give that a go.

NB: Make sure you rename the downloaded directory EDMC-Screenshot when you put it in you plugin folder

**Comment by romesc** [comment]
Wow, that 1.5 version just works. Really thanks. Good work.

**Comment by NoFoolLikeOne** [comment]
Thank you for raising the issue. 

I'm just getting used to working with github so haven't quite worked through the process yet

**Comment by NoFoolLikeOne** [comment]
@romsec There is a new release ready that fixes a bug with high def screenshots
