### ISSUE TITLE
New EDMC, does not show up for config, deletes images without converting

### ISSUE THREAD

**Issue by MalicT** [NoFoolLikeOne/EDMC-Screenshot#42]
With the update to EDMC, it seems this screenshot plugin has stopped working.

It does not show up under a tab to change its options, and when a screenshot is taken, it vanishes right after it is taken, and is not placed into the folder that it would have been previously.

**Comment by NoFoolLikeOne** [comment]
Have you downloaded the latest version?

I think I may do a bit of a rewrite in any case

**Comment by MalicT** [comment]
I had updated 6 days ago, checked the files to make sure, and then redownloaded it again, the first one must have corrupted as it is working now and not just deleting the files anymore
