### ISSUE TITLE
Screenshot: processing ..........

### ISSUE THREAD

**Issue by GettroLadalle** [NoFoolLikeOne/EDMC-Screenshot#8]
Hello,
I use the google translation sorry.
Thank you for your application.
I'm having a problem with your app
Description:
I take a screenshot, and the EDMC plugin marks me "Screenshot: processing ..."
and do not stop.
The directory of the system is created where it is needed, but remains desperately empty.
Do you have an idea of what I did wrong?
I'm work on:
Windows 10
In advance thank you for your answer.
Cordially.

**Comment by NoFoolLikeOne** [comment]
The problem appears to be with accented characters in the directory names.

**Comment by GettroLadalle** [comment]
Good evening,
Thank you for your reply.
I have actually re-uploaded all my documents into a new path without accent, and it works perfectly.
Thanks again.
Good flight commander.
